### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by stlang** [ThallingerLab/LDA2#1]
I am trying to utilize LDA2 using Debian 9. I was able to clone the repo and install LDA2 just fine. But I get an issue when starting a process. I get the stack:
```
Translating to mzXML
java.io.IOException: Cannot run program "msconvert/msconvert.exe": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:485)
	at at.tugraz.genome.lda.RawToMzxmlThread.startRawToMzxmlTranslation(RawToMzxmlThread.java:50)
	at at.tugraz.genome.lda.RawToMzxmlThread.run(RawToMzxmlThread.java:71)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 4 more
Translating to chrom from timer
Exception in thread "Timer-0" java.lang.ArithmeticException: / by zero
	at at.tugraz.genome.lda.BatchQuantThread.<init>(BatchQuantThread.java:95)
	at at.tugraz.genome.lda.LipidDataAnalyzer.handleTimerEvent(LipidDataAnalyzer.java:4002)
	at at.tugraz.genome.lda.LipidDataAnalyzer.access$100(LipidDataAnalyzer.java:200)
	at at.tugraz.genome.lda.LipidDataAnalyzer$ThreadSupervisor.run(LipidDataAnalyzer.java:4114)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Translating to mzXML
java.io.IOException: Cannot run program "msconvert/msconvert.exe": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:485)
	at at.tugraz.genome.lda.RawToMzxmlThread.startRawToMzxmlTranslation(RawToMzxmlThread.java:50)
	at at.tugraz.genome.lda.RawToMzxmlThread.run(RawToMzxmlThread.java:71)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 4 more
```

Clearly Proteowizard (msconvert) needs to be installed to a particular directory, but this was not specified in the README, or done so in the install. Proteowizard also does not supply the vendor specific converters for Linux as the license does not allow them to do so. With this said msconvert does not seem to be an option for Linux.

With that said, a possible work around would be to specify how msconvert should be run on the raw files, and these converted files can be used by LDA2 instead.

Are there other thoughts here? Do you think that this application will only be supported by Windows? Thanks for your time!

**Comment by hartler** [comment]
Dear stlang,

the LDA needs mzXML as input format (as stated in the LDA publication). Data in mzXML format work as well under Linux. For file conversion of raw data to mzXML, we use msconvert, which in turn uses vendor libraries to read the data. The problem, however, is that many vendor libraries are DLLs which cannot be run in any other operating system than Windows. I am currently not aware of any tool that supports raw file conversion of all vendor types in any other operating system than Windows.

Anyway, when you convert your data beforehand to mzXML (e.g. under Windows), you can use LDA2 on other operating systems too.
The msconvert command to convert your files to mzXML (under Windows) is:
msconvert --mzXML $PATH_TO_YOUR_FILE$

Best regards,
Juergen

PS: Sorry for the late reply, I overlooked the issue.
